#!/bin/bash

# Get the name of the C file from the command line argument
CFILE=$1

# Check that the argument was provided and is a C file
if [[ -z "$CFILE" || ${CFILE: -2} != ".c" ]]; then
    echo "Usage: $0 <C file>"
    exit 1
fi

# Generate the assembly code with GCC
gcc -S "$CFILE"

# Get the name of the output file by replacing the extension
OUTFILE="${CFILE%.c}.s"

# Move the assembly code to the output file
mv "${CFILE%.c}.s" "$OUTFILE"

echo "Assembly code saved to $OUTFILE"



